# Project file for a Scyndi Project
# Last modified: 16 Aug 2026

[AA_META]
01_TITLE=Star Story - Episode Three - The Interstellar Quest For Atlantis
02_CREATEDBY=Jeroen P. Broks
03_COPYRIGHT=(c) Jeroen P. Broks, 2026
04_LICENSE=Read License File For More Information
[ASSETS_MULTIDIR::JEROEN CC]
AUTHOR=Jeroen P. Broks
NOTES=This file is licensed under a Creative Commons - By Attribution - Non-Commercial - Share-Alike license
PACKAGE=Assets
USE=Y
[ASSETS_MULTIDIR::JEROEN EN LINVALA]
AUTHOR=Jeroen P. Broks & Linvala
NOTES=This file was dedicated to this project and may not be extracted or be reused or distributed without PRIOR written permission from Jeroen P. Broks.
PACKAGE=Assets
USE=Y
[ASSETS_MULTIDIR::JEROEN PRIVATE]
AUTHOR=Jeroen P. Broks
NOTES=This asset is property of Jeroen P. Broks and may NOT be exacted and reused without PRIOR written permission.
PACKAGE=Assets
USE=Y
[DIRECTORY]
SCI_ASSETS_MULTIDIR=Y
[DIRECTORY::LINUX]
SCI_ASSETS_SOURCE=src/Assets
*list:LIBRARIES
	/media/tricky/Scyndi/Projects/Applications/Scyndi/Libs/General
	/media/tricky/Scyndi/Projects/Applications/Scyndi/Libs/SCI
	/media/tricky/Scyndi/Projects/Applications/Slyvina/Apps/SCI/SCI_Exe/IntLibs
*end
*list:SOURCEFILES
	src/Code/Script
*end
[PACKAGE]
STORAGE=zlib
[PROJECT]
AUTHOR=Jeroen P. Broks
COPYRIGHT=(c) Jeroen P. Broks, 2026
CREATED=11 Feb 2026; 22:45:02
DEBUGJQLDIR=Debug
LICENSE=Read License File For More Information
OUTPUTNAME=Star Story - Episode Three - The Interstellar Quest For Atlantis
TITLE=Star Story - Episode Three - The Interstellar Quest For Atlantis
[SCI::MOUSE]
HIDE=Y
[SCI::SAVE]
DIR=Star Story 3
ID=723f786f349d090df9f17cc82837e97a-f8eddc0123850104b9196846a5def538
[SCI::WINDOW]
ALTHEIGHT=90
ALTWIDTH=98
CAPTION=Star Story - Episode Three - The Interstellar Quest For Atlantis
FULL SCREEN=N
USEALT=Y
WINADEPTALT=Y
WINHEIGHT=1000
WINWIDTH=1200
ALTHEIGHT=800
ALTWIDTH=1400
WINHEIGHT=85%
WINWIDTH=99%
[SCRIPT]
BYTECODE=Y
PACKAGE=Assets
